//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace employee
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class hotelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new hotelEntities object using the connection string found in the 'hotelEntities' section of the application configuration file.
        /// </summary>
        public hotelEntities() : base("name=hotelEntities", "hotelEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hotelEntities object.
        /// </summary>
        public hotelEntities(string connectionString) : base(connectionString, "hotelEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hotelEntities object.
        /// </summary>
        public hotelEntities(EntityConnection connection) : base(connection, "hotelEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<booking> booking
        {
            get
            {
                if ((_booking == null))
                {
                    _booking = base.CreateObjectSet<booking>("booking");
                }
                return _booking;
            }
        }
        private ObjectSet<booking> _booking;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<customer> customer
        {
            get
            {
                if ((_customer == null))
                {
                    _customer = base.CreateObjectSet<customer>("customer");
                }
                return _customer;
            }
        }
        private ObjectSet<customer> _customer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hotel> hotel
        {
            get
            {
                if ((_hotel == null))
                {
                    _hotel = base.CreateObjectSet<hotel>("hotel");
                }
                return _hotel;
            }
        }
        private ObjectSet<hotel> _hotel;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the booking EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobooking(booking booking)
        {
            base.AddObject("booking", booking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the customer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocustomer(customer customer)
        {
            base.AddObject("customer", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hotel EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohotel(hotel hotel)
        {
            base.AddObject("hotel", hotel);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new booking object.
        /// </summary>
        /// <param name="by_customer_email">Initial value of the by_customer_email property.</param>
        /// <param name="in_hotel_hid">Initial value of the in_hotel_hid property.</param>
        /// <param name="at">Initial value of the at property.</param>
        /// <param name="duration">Initial value of the duration property.</param>
        /// <param name="roomNr">Initial value of the roomNr property.</param>
        /// <param name="numAdults">Initial value of the numAdults property.</param>
        /// <param name="numChilds">Initial value of the numChilds property.</param>
        public static booking Createbooking(global::System.String by_customer_email, global::System.Int32 in_hotel_hid, global::System.String at, global::System.Int32 duration, global::System.Int32 roomNr, global::System.Int32 numAdults, global::System.Int32 numChilds)
        {
            booking booking = new booking();
            booking.by_customer_email = by_customer_email;
            booking.in_hotel_hid = in_hotel_hid;
            booking.at = at;
            booking.duration = duration;
            booking.roomNr = roomNr;
            booking.numAdults = numAdults;
            booking.numChilds = numChilds;
            return booking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String by_customer_email
        {
            get
            {
                return _by_customer_email;
            }
            set
            {
                if (_by_customer_email != value)
                {
                    Onby_customer_emailChanging(value);
                    ReportPropertyChanging("by_customer_email");
                    _by_customer_email = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("by_customer_email");
                    Onby_customer_emailChanged();
                }
            }
        }
        private global::System.String _by_customer_email;
        partial void Onby_customer_emailChanging(global::System.String value);
        partial void Onby_customer_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 in_hotel_hid
        {
            get
            {
                return _in_hotel_hid;
            }
            set
            {
                if (_in_hotel_hid != value)
                {
                    Onin_hotel_hidChanging(value);
                    ReportPropertyChanging("in_hotel_hid");
                    _in_hotel_hid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("in_hotel_hid");
                    Onin_hotel_hidChanged();
                }
            }
        }
        private global::System.Int32 _in_hotel_hid;
        partial void Onin_hotel_hidChanging(global::System.Int32 value);
        partial void Onin_hotel_hidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String at
        {
            get
            {
                return _at;
            }
            set
            {
                if (_at != value)
                {
                    OnatChanging(value);
                    ReportPropertyChanging("at");
                    _at = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("at");
                    OnatChanged();
                }
            }
        }
        private global::System.String _at;
        partial void OnatChanging(global::System.String value);
        partial void OnatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 duration
        {
            get
            {
                return _duration;
            }
            set
            {
                if (_duration != value)
                {
                    OndurationChanging(value);
                    ReportPropertyChanging("duration");
                    _duration = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("duration");
                    OndurationChanged();
                }
            }
        }
        private global::System.Int32 _duration;
        partial void OndurationChanging(global::System.Int32 value);
        partial void OndurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roomNr
        {
            get
            {
                return _roomNr;
            }
            set
            {
                if (_roomNr != value)
                {
                    OnroomNrChanging(value);
                    ReportPropertyChanging("roomNr");
                    _roomNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("roomNr");
                    OnroomNrChanged();
                }
            }
        }
        private global::System.Int32 _roomNr;
        partial void OnroomNrChanging(global::System.Int32 value);
        partial void OnroomNrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numAdults
        {
            get
            {
                return _numAdults;
            }
            set
            {
                if (_numAdults != value)
                {
                    OnnumAdultsChanging(value);
                    ReportPropertyChanging("numAdults");
                    _numAdults = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numAdults");
                    OnnumAdultsChanged();
                }
            }
        }
        private global::System.Int32 _numAdults;
        partial void OnnumAdultsChanging(global::System.Int32 value);
        partial void OnnumAdultsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numChilds
        {
            get
            {
                return _numChilds;
            }
            set
            {
                if (_numChilds != value)
                {
                    OnnumChildsChanging(value);
                    ReportPropertyChanging("numChilds");
                    _numChilds = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numChilds");
                    OnnumChildsChanged();
                }
            }
        }
        private global::System.Int32 _numChilds;
        partial void OnnumChildsChanging(global::System.Int32 value);
        partial void OnnumChildsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new customer object.
        /// </summary>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="pwd">Initial value of the pwd property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="adr">Initial value of the adr property.</param>
        /// <param name="tel">Initial value of the tel property.</param>
        public static customer Createcustomer(global::System.String email, global::System.String pwd, global::System.String name, global::System.String adr, global::System.Decimal tel)
        {
            customer customer = new customer();
            customer.email = email;
            customer.pwd = pwd;
            customer.name = name;
            customer.adr = adr;
            customer.tel = tel;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                if (_email != value)
                {
                    OnemailChanging(value);
                    ReportPropertyChanging("email");
                    _email = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("email");
                    OnemailChanged();
                }
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pwd
        {
            get
            {
                return _pwd;
            }
            set
            {
                if (_pwd != value)
                {
                    OnpwdChanging(value);
                    ReportPropertyChanging("pwd");
                    _pwd = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("pwd");
                    OnpwdChanged();
                }
            }
        }
        private global::System.String _pwd;
        partial void OnpwdChanging(global::System.String value);
        partial void OnpwdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adr
        {
            get
            {
                return _adr;
            }
            set
            {
                if (_adr != value)
                {
                    OnadrChanging(value);
                    ReportPropertyChanging("adr");
                    _adr = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("adr");
                    OnadrChanged();
                }
            }
        }
        private global::System.String _adr;
        partial void OnadrChanging(global::System.String value);
        partial void OnadrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal tel
        {
            get
            {
                return _tel;
            }
            set
            {
                if (_tel != value)
                {
                    OntelChanging(value);
                    ReportPropertyChanging("tel");
                    _tel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tel");
                    OntelChanged();
                }
            }
        }
        private global::System.Decimal _tel;
        partial void OntelChanging(global::System.Decimal value);
        partial void OntelChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="hotel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hotel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hotel object.
        /// </summary>
        /// <param name="hid">Initial value of the hid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="adr">Initial value of the adr property.</param>
        public static hotel Createhotel(global::System.Int32 hid, global::System.String name, global::System.String adr)
        {
            hotel hotel = new hotel();
            hotel.hid = hid;
            hotel.name = name;
            hotel.adr = adr;
            return hotel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hid
        {
            get
            {
                return _hid;
            }
            set
            {
                if (_hid != value)
                {
                    OnhidChanging(value);
                    ReportPropertyChanging("hid");
                    _hid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hid");
                    OnhidChanged();
                }
            }
        }
        private global::System.Int32 _hid;
        partial void OnhidChanging(global::System.Int32 value);
        partial void OnhidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adr
        {
            get
            {
                return _adr;
            }
            set
            {
                if (_adr != value)
                {
                    OnadrChanging(value);
                    ReportPropertyChanging("adr");
                    _adr = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("adr");
                    OnadrChanged();
                }
            }
        }
        private global::System.String _adr;
        partial void OnadrChanging(global::System.String value);
        partial void OnadrChanged();

        #endregion
    
    }

    #endregion
    
}
