USE [master]
GO

/****** Object:  Database [hotel]    Script Date: 03/27/2012 13:22:10 ******/
CREATE DATABASE [hotel] ON  PRIMARY 
( NAME = N'hotel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\hotel.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'hotel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\hotel_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [hotel] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hotel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hotel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hotel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hotel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hotel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hotel] SET ARITHABORT OFF 
GO

ALTER DATABASE [hotel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hotel] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [hotel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hotel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hotel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hotel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hotel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hotel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hotel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hotel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hotel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hotel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hotel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hotel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hotel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hotel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hotel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hotel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hotel] SET  READ_WRITE 
GO

ALTER DATABASE [hotel] SET RECOVERY FULL 
GO

ALTER DATABASE [hotel] SET  MULTI_USER 
GO

ALTER DATABASE [hotel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hotel] SET DB_CHAINING OFF 
GO

