//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employee.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://myxcode.at/")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private employee.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private employee.ServiceReference1.Hotel HotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtField;
        
        private int DurationField;
        
        private int RoomNrField;
        
        private int NumAdultsField;
        
        private int NumChildsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public employee.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public employee.ServiceReference1.Hotel Hotel {
            get {
                return this.HotelField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelField, value) != true)) {
                    this.HotelField = value;
                    this.RaisePropertyChanged("Hotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string At {
            get {
                return this.AtField;
            }
            set {
                if ((object.ReferenceEquals(this.AtField, value) != true)) {
                    this.AtField = value;
                    this.RaisePropertyChanged("At");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int RoomNr {
            get {
                return this.RoomNrField;
            }
            set {
                if ((this.RoomNrField.Equals(value) != true)) {
                    this.RoomNrField = value;
                    this.RaisePropertyChanged("RoomNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NumAdults {
            get {
                return this.NumAdultsField;
            }
            set {
                if ((this.NumAdultsField.Equals(value) != true)) {
                    this.NumAdultsField = value;
                    this.RaisePropertyChanged("NumAdults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NumChilds {
            get {
                return this.NumChildsField;
            }
            set {
                if ((this.NumChildsField.Equals(value) != true)) {
                    this.NumChildsField = value;
                    this.RaisePropertyChanged("NumChilds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://myxcode.at/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrField;
        
        private decimal TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToolTipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Adr {
            get {
                return this.AdrField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrField, value) != true)) {
                    this.AdrField = value;
                    this.RaisePropertyChanged("Adr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Tel {
            get {
                return this.TelField;
            }
            set {
                if ((this.TelField.Equals(value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ToolTip {
            get {
                return this.ToolTipField;
            }
            set {
                if ((object.ReferenceEquals(this.ToolTipField, value) != true)) {
                    this.ToolTipField = value;
                    this.RaisePropertyChanged("ToolTip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://myxcode.at/")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Hid {
            get {
                return this.HidField;
            }
            set {
                if ((this.HidField.Equals(value) != true)) {
                    this.HidField = value;
                    this.RaisePropertyChanged("Hid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Adr {
            get {
                return this.AdrField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrField, value) != true)) {
                    this.AdrField = value;
                    this.RaisePropertyChanged("Adr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myxcode.at/", ConfigurationName="ServiceReference1.ServerSoap")]
    public interface ServerSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/Authenticate", ReplyAction="*")]
        employee.ServiceReference1.AuthenticateResponse Authenticate(employee.ServiceReference1.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/Register", ReplyAction="*")]
        employee.ServiceReference1.RegisterResponse Register(employee.ServiceReference1.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/ListBookings", ReplyAction="*")]
        employee.ServiceReference1.ListBookingsResponse ListBookings(employee.ServiceReference1.ListBookingsRequest request);
        
        // CODEGEN: Generating message contract since element name ListBookingsByHidResult from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/ListBookingsByHid", ReplyAction="*")]
        employee.ServiceReference1.ListBookingsByHidResponse ListBookingsByHid(employee.ServiceReference1.ListBookingsByHidRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/NewBooking", ReplyAction="*")]
        employee.ServiceReference1.NewBookingResponse NewBooking(employee.ServiceReference1.NewBookingRequest request);
        
        // CODEGEN: Generating message contract since element name ListHotelsResult from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/ListHotels", ReplyAction="*")]
        employee.ServiceReference1.ListHotelsResponse ListHotels(employee.ServiceReference1.ListHotelsRequest request);
        
        // CODEGEN: Generating message contract since element name HotelInfoResult from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/HotelInfo", ReplyAction="*")]
        employee.ServiceReference1.HotelInfoResponse HotelInfo(employee.ServiceReference1.HotelInfoRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/EditBooking", ReplyAction="*")]
        employee.ServiceReference1.EditBookingResponse EditBooking(employee.ServiceReference1.EditBookingRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://myxcode.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myxcode.at/DeleteBooking", ReplyAction="*")]
        employee.ServiceReference1.DeleteBookingResponse DeleteBooking(employee.ServiceReference1.DeleteBookingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(employee.ServiceReference1.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string email, string pwd) {
            this.email = email;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(employee.ServiceReference1.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(int AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(employee.ServiceReference1.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string adr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tel;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string email, string pwd, string name, string adr, string tel) {
            this.email = email;
            this.pwd = pwd;
            this.name = name;
            this.adr = adr;
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(employee.ServiceReference1.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(bool RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListBookings", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.ListBookingsRequestBody Body;
        
        public ListBookingsRequest() {
        }
        
        public ListBookingsRequest(employee.ServiceReference1.ListBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class ListBookingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ListBookingsRequestBody() {
        }
        
        public ListBookingsRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListBookingsResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.ListBookingsResponseBody Body;
        
        public ListBookingsResponse() {
        }
        
        public ListBookingsResponse(employee.ServiceReference1.ListBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class ListBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public employee.ServiceReference1.Booking[] ListBookingsResult;
        
        public ListBookingsResponseBody() {
        }
        
        public ListBookingsResponseBody(employee.ServiceReference1.Booking[] ListBookingsResult) {
            this.ListBookingsResult = ListBookingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListBookingsByHidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListBookingsByHid", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.ListBookingsByHidRequestBody Body;
        
        public ListBookingsByHidRequest() {
        }
        
        public ListBookingsByHidRequest(employee.ServiceReference1.ListBookingsByHidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class ListBookingsByHidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int hid;
        
        public ListBookingsByHidRequestBody() {
        }
        
        public ListBookingsByHidRequestBody(int hid) {
            this.hid = hid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListBookingsByHidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListBookingsByHidResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.ListBookingsByHidResponseBody Body;
        
        public ListBookingsByHidResponse() {
        }
        
        public ListBookingsByHidResponse(employee.ServiceReference1.ListBookingsByHidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class ListBookingsByHidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public employee.ServiceReference1.Booking[] ListBookingsByHidResult;
        
        public ListBookingsByHidResponseBody() {
        }
        
        public ListBookingsByHidResponseBody(employee.ServiceReference1.Booking[] ListBookingsByHidResult) {
            this.ListBookingsByHidResult = ListBookingsByHidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewBooking", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.NewBookingRequestBody Body;
        
        public NewBookingRequest() {
        }
        
        public NewBookingRequest(employee.ServiceReference1.NewBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class NewBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int hid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string at;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int roomNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numAdults;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int numChilds;
        
        public NewBookingRequestBody() {
        }
        
        public NewBookingRequestBody(string email, int hid, string at, int duration, int roomNr, int numAdults, int numChilds) {
            this.email = email;
            this.hid = hid;
            this.at = at;
            this.duration = duration;
            this.roomNr = roomNr;
            this.numAdults = numAdults;
            this.numChilds = numChilds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewBookingResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.NewBookingResponseBody Body;
        
        public NewBookingResponse() {
        }
        
        public NewBookingResponse(employee.ServiceReference1.NewBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class NewBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewBookingResult;
        
        public NewBookingResponseBody() {
        }
        
        public NewBookingResponseBody(bool NewBookingResult) {
            this.NewBookingResult = NewBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListHotelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListHotels", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.ListHotelsRequestBody Body;
        
        public ListHotelsRequest() {
        }
        
        public ListHotelsRequest(employee.ServiceReference1.ListHotelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListHotelsRequestBody {
        
        public ListHotelsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListHotelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListHotelsResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.ListHotelsResponseBody Body;
        
        public ListHotelsResponse() {
        }
        
        public ListHotelsResponse(employee.ServiceReference1.ListHotelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class ListHotelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public employee.ServiceReference1.Hotel[] ListHotelsResult;
        
        public ListHotelsResponseBody() {
        }
        
        public ListHotelsResponseBody(employee.ServiceReference1.Hotel[] ListHotelsResult) {
            this.ListHotelsResult = ListHotelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HotelInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HotelInfo", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.HotelInfoRequestBody Body;
        
        public HotelInfoRequest() {
        }
        
        public HotelInfoRequest(employee.ServiceReference1.HotelInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class HotelInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int hid;
        
        public HotelInfoRequestBody() {
        }
        
        public HotelInfoRequestBody(int hid) {
            this.hid = hid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HotelInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HotelInfoResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.HotelInfoResponseBody Body;
        
        public HotelInfoResponse() {
        }
        
        public HotelInfoResponse(employee.ServiceReference1.HotelInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class HotelInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public employee.ServiceReference1.Hotel HotelInfoResult;
        
        public HotelInfoResponseBody() {
        }
        
        public HotelInfoResponseBody(employee.ServiceReference1.Hotel HotelInfoResult) {
            this.HotelInfoResult = HotelInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditBooking", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.EditBookingRequestBody Body;
        
        public EditBookingRequest() {
        }
        
        public EditBookingRequest(employee.ServiceReference1.EditBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class EditBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int hid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string at;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int roomNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numAdults;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int numChilds;
        
        public EditBookingRequestBody() {
        }
        
        public EditBookingRequestBody(string email, int hid, string at, int duration, int roomNr, int numAdults, int numChilds) {
            this.email = email;
            this.hid = hid;
            this.at = at;
            this.duration = duration;
            this.roomNr = roomNr;
            this.numAdults = numAdults;
            this.numChilds = numChilds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditBookingResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.EditBookingResponseBody Body;
        
        public EditBookingResponse() {
        }
        
        public EditBookingResponse(employee.ServiceReference1.EditBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class EditBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditBookingResult;
        
        public EditBookingResponseBody() {
        }
        
        public EditBookingResponseBody(bool EditBookingResult) {
            this.EditBookingResult = EditBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBooking", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.DeleteBookingRequestBody Body;
        
        public DeleteBookingRequest() {
        }
        
        public DeleteBookingRequest(employee.ServiceReference1.DeleteBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class DeleteBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int hid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string at;
        
        public DeleteBookingRequestBody() {
        }
        
        public DeleteBookingRequestBody(string email, int hid, string at) {
            this.email = email;
            this.hid = hid;
            this.at = at;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBookingResponse", Namespace="http://myxcode.at/", Order=0)]
        public employee.ServiceReference1.DeleteBookingResponseBody Body;
        
        public DeleteBookingResponse() {
        }
        
        public DeleteBookingResponse(employee.ServiceReference1.DeleteBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myxcode.at/")]
    public partial class DeleteBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteBookingResult;
        
        public DeleteBookingResponseBody() {
        }
        
        public DeleteBookingResponseBody(bool DeleteBookingResult) {
            this.DeleteBookingResult = DeleteBookingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServerSoapChannel : employee.ServiceReference1.ServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerSoapClient : System.ServiceModel.ClientBase<employee.ServiceReference1.ServerSoap>, employee.ServiceReference1.ServerSoap {
        
        public ServerSoapClient() {
        }
        
        public ServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.AuthenticateResponse employee.ServiceReference1.ServerSoap.Authenticate(employee.ServiceReference1.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public int Authenticate(string email, string pwd) {
            employee.ServiceReference1.AuthenticateRequest inValue = new employee.ServiceReference1.AuthenticateRequest();
            inValue.Body = new employee.ServiceReference1.AuthenticateRequestBody();
            inValue.Body.email = email;
            inValue.Body.pwd = pwd;
            employee.ServiceReference1.AuthenticateResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.RegisterResponse employee.ServiceReference1.ServerSoap.Register(employee.ServiceReference1.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public bool Register(string email, string pwd, string name, string adr, string tel) {
            employee.ServiceReference1.RegisterRequest inValue = new employee.ServiceReference1.RegisterRequest();
            inValue.Body = new employee.ServiceReference1.RegisterRequestBody();
            inValue.Body.email = email;
            inValue.Body.pwd = pwd;
            inValue.Body.name = name;
            inValue.Body.adr = adr;
            inValue.Body.tel = tel;
            employee.ServiceReference1.RegisterResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.ListBookingsResponse employee.ServiceReference1.ServerSoap.ListBookings(employee.ServiceReference1.ListBookingsRequest request) {
            return base.Channel.ListBookings(request);
        }
        
        public employee.ServiceReference1.Booking[] ListBookings(string email) {
            employee.ServiceReference1.ListBookingsRequest inValue = new employee.ServiceReference1.ListBookingsRequest();
            inValue.Body = new employee.ServiceReference1.ListBookingsRequestBody();
            inValue.Body.email = email;
            employee.ServiceReference1.ListBookingsResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).ListBookings(inValue);
            return retVal.Body.ListBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.ListBookingsByHidResponse employee.ServiceReference1.ServerSoap.ListBookingsByHid(employee.ServiceReference1.ListBookingsByHidRequest request) {
            return base.Channel.ListBookingsByHid(request);
        }
        
        public employee.ServiceReference1.Booking[] ListBookingsByHid(int hid) {
            employee.ServiceReference1.ListBookingsByHidRequest inValue = new employee.ServiceReference1.ListBookingsByHidRequest();
            inValue.Body = new employee.ServiceReference1.ListBookingsByHidRequestBody();
            inValue.Body.hid = hid;
            employee.ServiceReference1.ListBookingsByHidResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).ListBookingsByHid(inValue);
            return retVal.Body.ListBookingsByHidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.NewBookingResponse employee.ServiceReference1.ServerSoap.NewBooking(employee.ServiceReference1.NewBookingRequest request) {
            return base.Channel.NewBooking(request);
        }
        
        public bool NewBooking(string email, int hid, string at, int duration, int roomNr, int numAdults, int numChilds) {
            employee.ServiceReference1.NewBookingRequest inValue = new employee.ServiceReference1.NewBookingRequest();
            inValue.Body = new employee.ServiceReference1.NewBookingRequestBody();
            inValue.Body.email = email;
            inValue.Body.hid = hid;
            inValue.Body.at = at;
            inValue.Body.duration = duration;
            inValue.Body.roomNr = roomNr;
            inValue.Body.numAdults = numAdults;
            inValue.Body.numChilds = numChilds;
            employee.ServiceReference1.NewBookingResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).NewBooking(inValue);
            return retVal.Body.NewBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.ListHotelsResponse employee.ServiceReference1.ServerSoap.ListHotels(employee.ServiceReference1.ListHotelsRequest request) {
            return base.Channel.ListHotels(request);
        }
        
        public employee.ServiceReference1.Hotel[] ListHotels() {
            employee.ServiceReference1.ListHotelsRequest inValue = new employee.ServiceReference1.ListHotelsRequest();
            inValue.Body = new employee.ServiceReference1.ListHotelsRequestBody();
            employee.ServiceReference1.ListHotelsResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).ListHotels(inValue);
            return retVal.Body.ListHotelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.HotelInfoResponse employee.ServiceReference1.ServerSoap.HotelInfo(employee.ServiceReference1.HotelInfoRequest request) {
            return base.Channel.HotelInfo(request);
        }
        
        public employee.ServiceReference1.Hotel HotelInfo(int hid) {
            employee.ServiceReference1.HotelInfoRequest inValue = new employee.ServiceReference1.HotelInfoRequest();
            inValue.Body = new employee.ServiceReference1.HotelInfoRequestBody();
            inValue.Body.hid = hid;
            employee.ServiceReference1.HotelInfoResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).HotelInfo(inValue);
            return retVal.Body.HotelInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.EditBookingResponse employee.ServiceReference1.ServerSoap.EditBooking(employee.ServiceReference1.EditBookingRequest request) {
            return base.Channel.EditBooking(request);
        }
        
        public bool EditBooking(string email, int hid, string at, int duration, int roomNr, int numAdults, int numChilds) {
            employee.ServiceReference1.EditBookingRequest inValue = new employee.ServiceReference1.EditBookingRequest();
            inValue.Body = new employee.ServiceReference1.EditBookingRequestBody();
            inValue.Body.email = email;
            inValue.Body.hid = hid;
            inValue.Body.at = at;
            inValue.Body.duration = duration;
            inValue.Body.roomNr = roomNr;
            inValue.Body.numAdults = numAdults;
            inValue.Body.numChilds = numChilds;
            employee.ServiceReference1.EditBookingResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).EditBooking(inValue);
            return retVal.Body.EditBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        employee.ServiceReference1.DeleteBookingResponse employee.ServiceReference1.ServerSoap.DeleteBooking(employee.ServiceReference1.DeleteBookingRequest request) {
            return base.Channel.DeleteBooking(request);
        }
        
        public bool DeleteBooking(string email, int hid, string at) {
            employee.ServiceReference1.DeleteBookingRequest inValue = new employee.ServiceReference1.DeleteBookingRequest();
            inValue.Body = new employee.ServiceReference1.DeleteBookingRequestBody();
            inValue.Body.email = email;
            inValue.Body.hid = hid;
            inValue.Body.at = at;
            employee.ServiceReference1.DeleteBookingResponse retVal = ((employee.ServiceReference1.ServerSoap)(this)).DeleteBooking(inValue);
            return retVal.Body.DeleteBookingResult;
        }
    }
}
